### PR TITLE
Add conceptSet subsetting; fix condition generation

### LINKED ISSUE #166: Consider to have an option to subset the vocabulary to a set to certain concepts

### LINKED ISSUE #206: Currently mockConditionOccurrence creates one record per person and condition concept
If you use full vocabularies this is too much, could we consider to set the numberRecords as a function of the person and not the number of condition concepts in concept table.

### LINKED ISSUE #239: Use recordPerson independenlty to the number of concepts
Current behaviour will make things crash if many concepts are provided

### PR DESCRIPTION
**Pull request by ilovemane**
Introduce subsetVocabularyTables (R/vocabularySubset.R) to allow subsetting assembled vocabulary tables to a provided conceptSet while preserving directly related rows (relationships, ancestors, synonyms, drug strength). Add a conceptSet parameter and pass-through to mockCdmReference, mockVocabularyTables, and mockVocabularySet so vocab loading can be limited. Fix mockConditionOccurrence to scale generated rows by number of people (recordPerson * nPerson) and handle single-concept sampling correctly. Update docs (.Rd and README) to document the new conceptSet argument and wording fixes. Update tests to use snake_case, add tests for conceptSet behavior and condition occurrence scaling, and adjust/mock vocabulary table tests. Also tidy .Rbuildignore and .gitignore entries.

### CODE REVIEW

File: R/vocabularySubset.R [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+    conceptColumns <- conceptColumns[grepl("concept_id$", conceptColumns)]
+    conceptColumns <- intersect(conceptColumns, colnames(cdm[[tableName]]))
+
+    if (length(conceptColumns) == 0) {
+      next
+    }
+
+    table <- cdm[[tableName]]
+
+    for (column in conceptColumns) {
```
Comment (catalamarti) [inline R/vocabularySubset.R:200]: be careful this will eliminate records if unit concept id is not included in the concept set

**Review by catalamarti — CHANGES_REQUESTED** [review]

File: R/mockConditionOccurrence.R
Comment (catalamarti) [inline R/mockConditionOccurrence.R]: to change definition
